#!/usr/bin/env python3
# tmux new -s modpro-of3
# python monitor_manifests.py | tee monitor.log

from pathlib import Path
import subprocess
import time
import smtplib
from email.message import EmailMessage
import socket
import sys

WORKFLOW_DIR = Path("/scicomp/groups/modpro").resolve()
<<<<<<< HEAD
SNAKEFILE = WORKFLOW_DIR / "Snakefile-mondays"
MANIFEST_DIR = WORKFLOW_DIR / "manifests"
DONE_DIR = MANIFEST_DIR / ".processed"
DONE_DIR.mkdir(exist_ok=True)
WORKFLOW_DIR = Path("/scicomp/groups/modpro").resolve()
=======
MONDAY_SNAKEFILE = WORKFLOW_DIR / "Snakefile-mondays"
THURSDAY_SNAKEFILE = WORKFLOW_DIR / "Snakefile-thursdays"

MONDAY_MANIFEST_DIR = WORKFLOW_DIR / "manifests"
THURSDAY_MANIFEST_DIR = WORKFLOW_DIR / "manifests" / "rosetta_runs"

MONDAY_DONE_DIR = MONDAY_MANIFEST_DIR / ".processed"
THURSDAY_DONE_DIR = THURSDAY_MANIFEST_DIR / ".processed"

MONDAY_DONE_DIR.mkdir(exist_ok=True)
THURSDAY_DONE_DIR.mkdir(exist_ok=True)

MONDAY_CORES = "64"
THURSDAY_CORES = "32"

#WORKFLOW_DIR = Path("/scicomp/groups/modpro").resolve()

>>>>>>> 2412ee9 (add monitoring for thursday job pdb files generated by nifi in the manifests dir as .tsv files with list of pdbs)
EMAIL_TO = "qxa4@cdc.gov"
EMAIL_FROM = "qxa4@cdc.gov"
POLL_SECONDS = 10
CORES = "8"

def send_failure_email(subject: str, body: str):
    msg = EmailMessage()
    msg["To"] = EMAIL_TO
    msg["From"] = EMAIL_FROM
    msg["Subject"] = subject
    msg.set_content(body)
<<<<<<< HEAD

    # Most HPC/Linux systems expose local sendmail via localhost.
    # If this fails, the error is printed before the monitor exits.
=======
>>>>>>> 2412ee9 (add monitoring for thursday job pdb files generated by nifi in the manifests dir as .tsv files with list of pdbs)
    with smtplib.SMTP("localhost") as smtp:
        smtp.send_message(msg)

def file_is_stable(path: Path, wait_seconds: int = 5) -> bool:
    size1 = path.stat().st_size
    time.sleep(wait_seconds)
    size2 = path.stat().st_size
    return size1 == size2

<<<<<<< HEAD
def run_snakemake(path: Path):
    mid = path.stem
    target = f"results/{mid}/final/ha1_selected.pdb"
    cmd = [
        "snakemake",
        "--snakefile", str(SNAKEFILE),
        "--directory", str(WORKFLOW_DIR),
        target,
        "--cores", CORES,
        "--rerun-incomplete",
    ]
    print(f"Running Snakemake for manifest: {path}", flush=True)
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        failed_marker = DONE_DIR / f"{path.name}.failed"
=======
def run_snakemake(
    label: str,
    path: Path,
    snakefile: Path,
    done_dir: Path,
    target: str,
    cores: str,
    extra_args=None,
):
    if extra_args is None:
        extra_args = []
    cmd = [
        "snakemake",
        "--snakefile", str(snakefile),
        "--directory", str(WORKFLOW_DIR),
        target,
        "--cores", cores,
        "--printshellcmds",
        "--rerun-incomplete",
        "--keep-going",
        "--latency-wait", "120",
    ] + extra_args
    print(f"Running {label} Snakemake for manifest: {path}", flush=True)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        failed_marker = done_dir / f"{path.name}.failed"
>>>>>>> 2412ee9 (add monitoring for thursday job pdb files generated by nifi in the manifests dir as .tsv files with list of pdbs)
        failed_marker.write_text(
            f"FAILED\n\nCommand:\n{' '.join(cmd)}\n\n"
            f"STDOUT:\n{result.stdout}\n\nSTDERR:\n{result.stderr}\n"
        )
<<<<<<< HEAD
        subject = f"[modpro] Snakemake failed for {path.name}"
        body = f"""
Snakemake failed and the manifest monitor is exiting.

=======
        subject = f"[modpro] {label} Snakemake failed for {path.name}"
        body = f"""
{label} Snakemake failed and the monitor is exiting.
>>>>>>> 2412ee9 (add monitoring for thursday job pdb files generated by nifi in the manifests dir as .tsv files with list of pdbs)
Host:
{socket.gethostname()}
Workflow directory:
{WORKFLOW_DIR}
<<<<<<< HEAD
=======
Snakefile:
{snakefile}
>>>>>>> 2412ee9 (add monitoring for thursday job pdb files generated by nifi in the manifests dir as .tsv files with list of pdbs)
Manifest:
{path}
Target:
{target}
Exit code:
{result.returncode}
Command:
{' '.join(cmd)}
STDOUT:
{result.stdout}
STDERR:
{result.stderr}
A failed marker was written to:
{failed_marker}
"""
<<<<<<< HEAD
        print("Snakemake FAILED. Sending failure email and exiting.", flush=True)
        print(result.stdout, flush=True)
        print(result.stderr, flush=True)
=======
        print(f"{label} Snakemake FAILED. Sending failure email and exiting.", flush=True)
        print(result.stdout, flush=True)
        print(result.stderr, flush=True)

>>>>>>> 2412ee9 (add monitoring for thursday job pdb files generated by nifi in the manifests dir as .tsv files with list of pdbs)
        try:
            send_failure_email(subject, body)
            print(f"Failure email sent to {EMAIL_TO}", flush=True)
        except Exception as email_error:
            print(f"Failed to send email: {email_error}", flush=True)
<<<<<<< HEAD
        sys.exit(result.returncode)
    print("Snakemake completed successfully", flush=True)
    done_marker = DONE_DIR / f"{path.name}.done"
    done_marker.write_text("done\n")

def main():
    if not SNAKEFILE.exists():
        msg = f"Snakefile not found: {SNAKEFILE}"
        try:
            send_failure_email("[modpro] Manifest monitor failed to start", msg)
        except Exception as email_error:
            print(f"Failed to send startup failure email: {email_error}", flush=True)
        raise SystemExit(msg)
    while True:
        for path in sorted(MANIFEST_DIR.glob("*.csv")):
            done_marker = DONE_DIR / f"{path.name}.done"
            failed_marker = DONE_DIR / f"{path.name}.failed"
            if done_marker.exists() or failed_marker.exists():
                continue
            if not file_is_stable(path):
                continue
            run_snakemake(path)
        time.sleep(POLL_SECONDS)

if __name__ == "__main__":
    main()
=======

        sys.exit(result.returncode)

    done_marker = done_dir / f"{path.name}.done"
    done_marker.write_text("done\n")

    print(f"{label} Snakemake completed successfully", flush=True)

def check_manifest(
    label: str,
    manifest_dir: Path,
    done_dir: Path,
    suffix: str,
    snakefile: Path,
    target_builder,
    cores: str,
    extra_args=None,
):
    found_work = False
    for path in sorted(manifest_dir.glob(f"*{suffix}")):
        if not path.is_file():
            continue
        if path.name.startswith("."):
            continue
        done_marker = done_dir / f"{path.name}.done"
        failed_marker = done_dir / f"{path.name}.failed"
        if done_marker.exists() or failed_marker.exists():
            continue
        print(f"Checking {label} manifest: {path}", flush=True)
        if not file_is_stable(path):
            print(f"File not stable yet: {path}", flush=True)
            continue
        found_work = True
        run_id = path.stem
        target = target_builder(run_id)

        run_snakemake(
            label=label,
            path=path,
            snakefile=snakefile,
            done_dir=done_dir,
            target=target,
            cores=cores,
            extra_args=extra_args,
        )
    return found_work

def monday_target(run_id: str) -> str:
    return f"results/{run_id}/openfold3/manifest.done"

def thursday_target(run_id: str) -> str:
    return f"results/final/{run_id}/thursday.done"

def main():
    for snakefile in [MONDAY_SNAKEFILE, THURSDAY_SNAKEFILE]:
        if not snakefile.exists():
            msg = f"Snakefile not found: {snakefile}"
            try:
                send_failure_email("[modpro] Combined monitor failed to start", msg)
            except Exception as email_error:
                print(f"Failed to send startup failure email: {email_error}", flush=True)
            raise SystemExit(msg)
    print("Combined manifest monitor started", flush=True)
    print(f"Workflow directory: {WORKFLOW_DIR}", flush=True)
    print(f"Monday Snakefile: {MONDAY_SNAKEFILE}", flush=True)
    print(f"Thursday Snakefile: {THURSDAY_SNAKEFILE}", flush=True)
    print(f"Monday manifest dir: {MONDAY_MANIFEST_DIR}", flush=True)
    print(f"Thursday manifest dir: {THURSDAY_MANIFEST_DIR}", flush=True)
    print(f"Polling every {POLL_SECONDS} seconds", flush=True)
    while True:
        monday_work = check_manifest(
            label="Monday/OpenFold3",
            manifest_dir=MONDAY_MANIFEST_DIR,
            done_dir=MONDAY_DONE_DIR,
            suffix=".csv",
            snakefile=MONDAY_SNAKEFILE,
            target_builder=monday_target,
            cores=MONDAY_CORES,
            extra_args=["--resources", "msa_slots=2", "inference_slots=1"],
        )
        thursday_work = check_manifest(
            label="Thursday/Rosetta",
            manifest_dir=THURSDAY_MANIFEST_DIR,
            done_dir=THURSDAY_DONE_DIR,
            suffix=".tsv",
            snakefile=THURSDAY_SNAKEFILE,
            target_builder=thursday_target,
            cores=THURSDAY_CORES,
        )
        if not monday_work and not thursday_work:
            print(f"No new manifests found. Sleeping {POLL_SECONDS}s...", flush=True)
        time.sleep(POLL_SECONDS)

if __name__ == "__main__":
    main()
>>>>>>> 2412ee9 (add monitoring for thursday job pdb files generated by nifi in the manifests dir as .tsv files with list of pdbs)
